// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/asynq/asynq.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Generic input message for flexible data
type DynamicInput struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Fields        map[string]*structpb.Value `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamicInput) Reset() {
	*x = DynamicInput{}
	mi := &file_proto_asynq_asynq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamicInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicInput) ProtoMessage() {}

func (x *DynamicInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asynq_asynq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicInput.ProtoReflect.Descriptor instead.
func (*DynamicInput) Descriptor() ([]byte, []int) {
	return file_proto_asynq_asynq_proto_rawDescGZIP(), []int{0}
}

func (x *DynamicInput) GetFields() map[string]*structpb.Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Workflow execution request
type ExecuteWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Input         *DynamicInput          `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Context       map[string]string      `protobuf:"bytes,3,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteWorkflowRequest) Reset() {
	*x = ExecuteWorkflowRequest{}
	mi := &file_proto_asynq_asynq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteWorkflowRequest) ProtoMessage() {}

func (x *ExecuteWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asynq_asynq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteWorkflowRequest.ProtoReflect.Descriptor instead.
func (*ExecuteWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_proto_asynq_asynq_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *ExecuteWorkflowRequest) GetInput() *DynamicInput {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ExecuteWorkflowRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

// Workflow execution response
type ExecuteWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteWorkflowResponse) Reset() {
	*x = ExecuteWorkflowResponse{}
	mi := &file_proto_asynq_asynq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteWorkflowResponse) ProtoMessage() {}

func (x *ExecuteWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asynq_asynq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteWorkflowResponse.ProtoReflect.Descriptor instead.
func (*ExecuteWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_proto_asynq_asynq_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteWorkflowResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecuteWorkflowResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *ExecuteWorkflowResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecuteWorkflowResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_asynq_asynq_proto protoreflect.FileDescriptor

const file_proto_asynq_asynq_proto_rawDesc = "" +
	"\n" +
	"\x17proto/asynq/asynq.proto\x12\x05asynq\x1a\x1cgoogle/protobuf/struct.proto\"\x9a\x01\n" +
	"\fDynamicInput\x127\n" +
	"\x06fields\x18\x01 \x03(\v2\x1f.asynq.DynamicInput.FieldsEntryR\x06fields\x1aQ\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\xe6\x01\n" +
	"\x16ExecuteWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12)\n" +
	"\x05input\x18\x02 \x01(\v2\x13.asynq.DynamicInputR\x05input\x12D\n" +
	"\acontext\x18\x03 \x03(\v2*.asynq.ExecuteWorkflowRequest.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8f\x01\n" +
	"\x17ExecuteWorkflowResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage2e\n" +
	"\x11AsyncQueueService\x12P\n" +
	"\x0fExecuteWorkflow\x12\x1d.asynq.ExecuteWorkflowRequest\x1a\x1e.asynq.ExecuteWorkflowResponseB\"Z github.com/yourusername/asynq/pbb\x06proto3"

var (
	file_proto_asynq_asynq_proto_rawDescOnce sync.Once
	file_proto_asynq_asynq_proto_rawDescData []byte
)

func file_proto_asynq_asynq_proto_rawDescGZIP() []byte {
	file_proto_asynq_asynq_proto_rawDescOnce.Do(func() {
		file_proto_asynq_asynq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_asynq_asynq_proto_rawDesc), len(file_proto_asynq_asynq_proto_rawDesc)))
	})
	return file_proto_asynq_asynq_proto_rawDescData
}

var file_proto_asynq_asynq_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_asynq_asynq_proto_goTypes = []any{
	(*DynamicInput)(nil),            // 0: asynq.DynamicInput
	(*ExecuteWorkflowRequest)(nil),  // 1: asynq.ExecuteWorkflowRequest
	(*ExecuteWorkflowResponse)(nil), // 2: asynq.ExecuteWorkflowResponse
	nil,                             // 3: asynq.DynamicInput.FieldsEntry
	nil,                             // 4: asynq.ExecuteWorkflowRequest.ContextEntry
	(*structpb.Value)(nil),          // 5: google.protobuf.Value
}
var file_proto_asynq_asynq_proto_depIdxs = []int32{
	3, // 0: asynq.DynamicInput.fields:type_name -> asynq.DynamicInput.FieldsEntry
	0, // 1: asynq.ExecuteWorkflowRequest.input:type_name -> asynq.DynamicInput
	4, // 2: asynq.ExecuteWorkflowRequest.context:type_name -> asynq.ExecuteWorkflowRequest.ContextEntry
	5, // 3: asynq.DynamicInput.FieldsEntry.value:type_name -> google.protobuf.Value
	1, // 4: asynq.AsyncQueueService.ExecuteWorkflow:input_type -> asynq.ExecuteWorkflowRequest
	2, // 5: asynq.AsyncQueueService.ExecuteWorkflow:output_type -> asynq.ExecuteWorkflowResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_asynq_asynq_proto_init() }
func file_proto_asynq_asynq_proto_init() {
	if File_proto_asynq_asynq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_asynq_asynq_proto_rawDesc), len(file_proto_asynq_asynq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_asynq_asynq_proto_goTypes,
		DependencyIndexes: file_proto_asynq_asynq_proto_depIdxs,
		MessageInfos:      file_proto_asynq_asynq_proto_msgTypes,
	}.Build()
	File_proto_asynq_asynq_proto = out.File
	file_proto_asynq_asynq_proto_goTypes = nil
	file_proto_asynq_asynq_proto_depIdxs = nil
}
